CiscoUcs/ucsm_apis

MANIFEST.in
=> updated Manifest

ucsm_apis/server/__init__.py, ucsm_apis/server/power.py, ucsm_apis/utils/__init__.py, ucsm_apis/utils/utils.py
Support for - 
```
- server power on
- server power off
- server power cycle wait
- server power cycle immediate
```
=> Power apis

README.rst
Added Install, Uninstall, License and History
=> updating readme

docs/conf.py, docs/index.rst
=> updating doc conf

docs/modules.rst
=> adding modules.rst

api_spec.md
=> updating api spec

ucsm_apis/server/power.py
Signed-off-by: ragupta-git <gupta.rahul13@gmail.com>
=> Added docstring and fixed raise error for serverpower APIs.

tests/system_test/connection/__init__.py, tests/system_test/connection/connection.cfg, tests/system_test/connection/info.py, tests/system_test/server/test_server_boot_order.py, tests/unit_test/server/test_ut_server_boot_order.py, ucsm_apis/server/boot.py
Added API boot_policy_order_exist and boot_order testcases.
=> Added API boot_policy_order_exist and boot_order testcases.

tests/system_test/server/test_server_boot_order.py, tests/system_test/server/test_server_boot_policy.py, ucsm_apis/server/boot.py
Added system test cases for boot policy.
=> Added system test cases for boot policy.

tests/system_test/network/__init__.py, tests/unit_test/admin/__init__.py, tests/unit_test/network/__init__.py, ucsm_apis/network/__init__.py
=> Adding structure for network APIs

ucsm_apis/admin/dns.py
=> Added DNS Server APIs

tests/system_test/admin/test_admin_user.py, tests/system_test/admin/test_call_home.py, ucsm_apis/admin/callhome.py, ucsm_apis/admin/keyring.py, ucsm_apis/admin/ldap.py, ucsm_apis/admin/locale.py, ucsm_apis/admin/radius.py, ucsm_apis/admin/role.py, ucsm_apis/admin/snmp.py, ucsm_apis/admin/syslog.py, ucsm_apis/admin/tacacsplus.py, ucsm_apis/admin/timezone.py, ucsm_apis/admin/user.py
=> Added Admin Related APIs.

setup.py, tests/unit_test/server/test_ut_server_power.py
=> Added unit tests for server power

tests/system_test/server/test_server_boot_order.py, tests/system_test/server/test_server_boot_policy.py, ucsm_apis/server/boot.py
Fixed issues related to boot APIs.
=> Fixed issues related to boot APIs

ucsm_apis/admin/dns.py
=> Corrected the variable name.

ucsm_apis/admin/locale.py
=> Added exists api for locale org configuration

ucsm_apis/admin/ldap.py
Added and modified exists api for ldap related config.
- adds exists api for ldap config
- adds exists api to configure group rules for a ldap provider
- modifies exists api to ignore 'order' if order=='lowest-available'
=> Added and modified exists api for ldap related config.

ucsm_apis/admin/radius.py
=> modified exists api for radius config

ucsm_apis/admin/tacacsplus.py
=> modified exists apis for tacacsplus config

ucsm_apis/admin/syslog.py
=> addes exists apis for syslog related config

ucsm_apis/admin/snmp.py
=> Added and modified exists api for snmp related config

ucsm_apis/admin/callhome.py
=> Added exists api and few fixes for callhome apis

ucsm_apis/admin/user.py
Added exists api for password strength and profile.
=> Added exists api for password strength and profile.

ucsm_apis/admin/timezone.py
=> Added exists api for timezone

ucsm_apis/admin/auth.py
Modified exists api to support multiple param set related to auth.
=> Modified exists api to support multiple param set related to auth.

ucsm_apis/server/boot.py
=> Added exist api for boot security and added device efi to boot order

hooks/check_ast.py, hooks/check_flake8.py, hooks/check_merge_conflict.py, hooks/util.py
Signed-off-by: Vikrant Balyan (vvb) <vvb@cisco.com>
=> checks that will be added as a part of the pre-commit hooks

ucsm_apis/server/power.py
Modified Power API to support ansible power module.
=> Modifed Power API to support ansible power module.

ucsm_apis/server/boot.py
Issue with comparing boot order for a boot policy.
=> Fixes the Issue52
